### ISSUE TITLE
Doesn't work on Sensu 0.20

### ISSUE THREAD

**Issue by georgespatton** [bimlendu/sensu-cachethq#4]
Either I am missing something from the documentation, but I am not able to get this to work with Sensu 0.20 and the latest version of CachetHQ.  Here is my configuration:

Just a simple test to trigger the handler.

cat checks/check_myserver.json

{
  "checks": {
    "check-www-cachethq": {
      "handlers": [ "cachethq" ],
      "command": "echo 'We are investigating an issue'; exit 2",
      "interval": 60,
      "cachethq" : {
        "component": {
          "name": "My Server",
          "id": "5"
        }
      },
      "subscribers": [ "myserver" ]
    }
   }

cat handlers/cachethq.json
{
  "handlers": {
    "cachethq": {
      "type": "pipe",
      "command": "/etc/sensu/handlers/cachethq.rb"
    }
  },
  "cachethq": {
    "api_url" : "https://mysite/api/v1",
    "api_token" : "mytoken"
  }
}

When I apply pull request https://github.com/bimlendu/sensu-cachethq/pull/3 I get the following error in the sensu server logs:

{"timestamp":"2015-11-17T03:27:33.874780+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/cachethq.rb","name":"cachethq"},"output":["Exception occured : 400 \"Bad Request\"\n/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:119:in `error!'\n/etc/sensu/handlers/cachethq.rb:56:in`verify_response'\n/etc/sensu/handlers/cachethq.rb:129:in `update_cachet'\n/etc/sensu/handlers/cachethq.rb:135:in`handle'\n/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in class:Handler'\n"]}

Without that change, I get the following error in the sensu server logs:

{"timestamp":"2015-11-16T18:27:33.487288+0000","level":"info","message":"handler output","handler":{"severities":["ok","critical","unknown"],"type":"pipe","command":"/etc/sensu/handlers/cachethq.rb","name":"cachethq"},"output":["Exception occured : undefined method `[]' for nil:NilClass\n/etc/sensu/handlers/cachethq.rb:73:in`component_id'\n/etc/sensu/handlers/cachethq.rb:125:in `handle'\n/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in`block in class:Handler'\n"]}

Something about line 73, it is not passing in one of the following parameters, but not sure which one:

 @event['client']['cachethq']['component']['id'] || @event['check']['cachethq']['component']['id']

Thanks for any guidance or help.

**Comment by bimlendu** [comment]
Since Cachethq is under rapid development, I am waiting for a stable v2.0.0 to be released. Probably endpoints have some changes.

In the meantime can you try the previous version of the plugin https://github.com/bimlendu/sensu-cachethq/blob/9914359fe70c7231fabc34551a1fbde2e598a602/cachethq.rb

**Comment by georgespatton** [comment]
I tried both the commit you suggest and latest, both didn't work.  Does my configuration seem correct?  What are the conditions that you have where it is working?  At the very least we can add some additional recommendations to the README.md for future users if there are environmental requirements.

**Comment by bimlendu** [comment]
Can you try with following check json.

```
{
"checks": {
"check-www-cachethq": {
"handlers": [ "cachethq" ],
"command": "echo 'We are investigating an issue'; (exit 2)",
"interval": 60,
"cachethq" : {
"component": {
"name": "My Server",
"id": "5"
}
},
"subscribers": [ "myserver" ]
}
}
```

The handlers original and the latest, bot works in my test machine. There is no environmental setup as such. The handler is very very simple. It just checks the output of the check and notifies CachetHQ accordingly. In your case the output of the check isn't proper.

Here is what is happening when I run the check command locally.

```
[root@sensu001 handlers_test]# echo 'We are investigating an issue'; exit 2
We are investigating an issue
exit
[ec2-user@sensu001 ~]$ echo $?
2
```

Notice that the check actually logs out the user running the command. I am not sure how this affects in sensu setup.

**Comment by bimlendu** [comment]
You can test the handler outside of the sensu environment. To do so, create a [sensu event json](https://sensuapp.org/docs/latest/events), and pipe it to the handler.

A very basic event json would be something like this:

```
{
    "client": {
        "name": "demo001"
    },
    "check": {
        "name": "check-www-cachethq",
        "output": "we are investigating an issue",
        "status": 2,
        "cachethq": {
            "component": {
                "id": "1",
                "name": "EC2 (N. Virginia)"
            }
        }
    },
    "occurrences": 1,
    "action": "create",
    "timestamp": 1447936582
}
```

Now in your cachehq handler _harcode_ the values that the handler reads from the cachethq.json config file.

```
def api_url
  'http://cachethq.host.com/api/v1'
end

def api_token
  'XXXXXXXXXXXXXXXXX'
end
```

And run it

```
cat event.json | /opt/sensu/embedded/bin/ruby cachethq.rb
```

**Comment by georgespatton** [comment]
I will try this out and let you know.  Thank you.

**Comment by georgespatton** [comment]
Followed your instructions.  I think it is because the API has changed.  Does this work for you using the latest version of cachethq?

cat event.json |   /opt/sensu/embedded/bin/ruby ../handlers/cachethq.rb

Exception occured : 400 "Bad Request"
/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:119:in `error!'
../handlers/cachethq.rb:56:in`verify_response'
../handlers/cachethq.rb:129:in `update_cachet'
../handlers/cachethq.rb:135:in`handle'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in class:Handler'

With debug:

cat event.json |   /opt/sensu/embedded/bin/ruby --debug ../handlers/cachethq.rb
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:1087 - cannot load such file -- rubygems/defaults/operating_system
Exception`LoadError' at /opt/sensu/embedded/lib/ruby/2.0.0/rubygems.rb:1096 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- sensu-handler
Exception`NoMethodError' at /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/specification.rb:1896 - undefined method `to_ary' for #<Gem::Specification:0x00000001b83228>
....
....
Using Ext extension for JSON.
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:50: warning: instance variable @separate_default_options not initialized
Exception`Errno::ENOENT' at /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/utils.rb:16 - No such file or directory - /etc/sensu/config.json
Exception `NoMethodError' at /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/utils.rb:62 - undefined method`deep_merge' for "demo001":String
Exception `Errno::EAGAIN' at /opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:153 - Resource temporarily unavailable - read would block
Exception`Errno::EAGAIN' at /opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:153 - Resource temporarily unavailable - read would block
Exception `Errno::EAGAIN' at /opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:153 - Resource temporarily unavailable - read would block
Exception`Errno::EAGAIN' at /opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:153 - Resource temporarily unavailable - read would block
Exception `Net::HTTPServerException' at /opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:119 - 400 "Bad Request"
Exception occured : 400 "Bad Request"
/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:119:in`error!'
../handlers/cachethq.rb:56:in `verify_response'
../handlers/cachethq.rb:129:in`update_cachet'
../handlers/cachethq.rb:135:in `handle'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in`block in class:Handler'

Note that a direct curl does work:

 curl -H "Content-Type: application/json;" -H "X-Cachet-Token: myapitoken" -d '{"name":"mycomponent","description":"An example description","status":3,"visible":1}' https://status.mysite.com/api/v1/incidents

**Comment by GhostLyrics** [comment]
For me that are two different scenarios:

If I run the query @georgespatton suggested:

``` none
testing@monitor-vm:/etc/apt/sources.list.d# curl -H "Content-Type: application/json;" -H "X-Cachet-Token: cOjQcFtOifxl0K7uJFfG" -d '{"name":"API","description":"something","status":3,"visible":1}' http://localhost/api/v1/incidents
{"errors":[{"id":"eaec7e8c-0898-4d66-903e-489d80eb17d2","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The message field is required."]}}]}
```

However, if I add the `message` field it works for curl. (Need to test the plugin too, but that might be a first hint.)

``` none
testing@monitor-vm:/etc/apt/sources.list.d# curl -H "Content-Type: application/json;" -H "X-Cachet-Token: cOjQcFtOifxl0K7uJFfG" -d '{"name":"API","description":"something","status":3,"visible":1,"message":"I have no clue"}' http://localhost/api/v1/incidents
{"data":{"name":"API","status":"3","message":"I have no clue","visible":1,"updated_at":"2016-01-05 18:57:59","created_at":"2016-01-05 18:57:59","id":2,"notify":true,"human_status":"Watching","component":null,"scheduled_at":"2016-01-05 18:57:59"}}
```

**Comment by georgespatton** [comment]
Thank you.
